#! /bin/bash

echo "This script installs the STDR Simulator."
echo "It is tested and works with Melodic."
echo "It also works with a forked version of the STDR"
echo "Simulator that compiles for Ubuntu Foxy/ROS Noetic."

old_dir=$(pwd)
STDR_WS=/tmp/stdr_ws

# Setup ROS
if [ ${#ROS_PACKAGE_PATH} -lt 1 ]
then
    ROS_VERS=($(ls /opt/ros))
    if [ ${#ROS_VERS[@]} -gt 1 ]
    then
        select ver in ${ROS_VERS[@]}; do echo $ver; break; done
        source /opt/ros/$ver/setup.bash
    elif [ ${#ROS_VERS[@]} -eq 0 ]
    then
        if [ -d /opt/ros ]
        then
            echo "The ROS installation is corrupted."
        else
            echo "ROS has not been installed."
        fi
        exit
    else
        ver=ROS_VERS
        source /opt/ros/$ver/setup.bash
    fi

    if [ ${#ROS_PACKAGE_PATH} -lt 1 ]
    then
        echo "ROS appears misconfigured.  It may not be installed or there may be another issue."
    fi
else 
    ver=$ROS_DISTRO
fi

if [ $ver == 'melodic' ]; then
    echo "Installing Qt4 dependencies that are not properly identified in package."
    echo "This requires sudo privileges."
    echo "sudo apt-get install -y libqt4-dev"
    sudo apt-get install -y libqt4-dev
fi

		
# Test if GIT is installed and install it if it is missing
GIT_EXE=$(which git)

echo "Checking for git"
if [ ${#GIT_EXE} -lt 1 ]; then
    echo "GIT needs to be installed."
    sudo apt-get install -y git
fi

echo "Checking of the STDR Simulator code is where it is expected"
if [ ! -d $STDR_WS/src/stdr_simulator ]; then
    echo "Cloning the STDR Simulator code"
    mkdir -p $STDR_WS/src
    git clone --branch $ver-devel https://github.com/cwru-eecs-275/stdr_simulator.git $STDR_WS/src
fi

cd $STDR_WS

which rosdep
ret=$?

if [ $ret -eq 0 ]; then
	echo "Install all dependencies using rosdep"
	rosdep install --from-paths src  --ignore-src -r -y
else
	echo "It appears rosdep is not available.  Attempting to install known packages manually."
    echo "It may be necessary to install rosdep and/or install packages manually."
    echo "This requires sudo privileges."
    if [ $ver == "noetic" ]; then
        echo "sudo apt-get install -y ros-$ver-map-server ros-$ver-qt-gui libqt5core5a libqt5gui5 libqt5widgets5 "
        sudo apt-get install -y ros-$ver-map-server ros-$ver-qt-gui libqt5core5a libqt5gui5 libqt5widgets5
    fi
    if [ $ver == "melodic" ]; then
        echo "sudo apt-get install -y ros-$ver-map-server libqt4-dev"
        sudo apt-get install -y ros-$ver-map-server libqt4-dev
    fi
fi

echo "Making the STDR Simulator."
catkin_make 

if [ $? -gt 0 ]; then
    echo "Problem compiling STDR Simulator.  Exiting."
    exit
fi

echo "Installing the STDR Simulator.  This requires sudo privileges."
sudo -- /bin/bash -c "source /opt/ros/$ver/setup.bash; catkin_make -DCMAKE_INSTALL_PREFIX=/opt/ros/$ver install" 

source /opt/ros/$ver/setup.bash
rospack find stdr_launchers
ret=$?

if [ $ret -eq 0 ]; then
    echo "It appears everything was installed successfully."
    echo "In a new terminal run the following commands to verify the STDR Simultor runs:"
    echo "source /opt/ros/$ver/setup.bash"
    echo "roslaunch stdr_launchers server_with_map_and_gui_plus_robot.launch"
else
    echo "It appears the installation did not succeed."
fi

